name: abstracts
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  intl: ^0.18.0
  go_router: ^10.0.0
  dio: ^5.3.2
  locator: ^0.0.0-dev.2
  awesome_snackbar_content: ^0.1.3
  flutter_bloc: ^8.1.3
  pretty_dio_logger: ^1.3.1
  dotted_border: ^2.0.0+3
  talker_bloc_logger: ^2.2.0
  liquid_swipe: ^3.1.0
  http: ^1.1.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  easy_pdf_viewer: ^1.0.7
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  #команды для запустка иконок 
  # flutter pub get
  # flutter pub run flutter_launcher_icons
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
